/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package inventorymanager.view;

import inventorymanager.controller.CategoryController;
import inventorymanager.controller.ProductController;
import inventorymanager.model.Category;
import inventorymanager.model.Product;
import inventorymanager.repository.CategoryRepository;
import java.util.ArrayList;
import java.util.List;
import java.util.stream.Collectors;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Gabote
 */
public class AddProductView extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AddProductView.class.getName());
    private final CategoryController cc;
    private final ProductController pc;

    /**
     * Creates new form AddProductView
     */
    public AddProductView(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        //CUSTOM
        this.cc = new CategoryController();
        this.pc = new ProductController();
        updateComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel_productId = new javax.swing.JLabel();
        jTextField_productIdInput = new javax.swing.JTextField();
        jTextField_productNameInput = new javax.swing.JTextField();
        jTextField_productPrice = new javax.swing.JTextField();
        jTextField_productStock = new javax.swing.JTextField();
        jLabel_productName = new javax.swing.JLabel();
        jLabel_productCategory = new javax.swing.JLabel();
        jLabel_productPrice = new javax.swing.JLabel();
        jLabel_productStock = new javax.swing.JLabel();
        jComboBox_productCategoryCmbBx = new javax.swing.JComboBox<>();
        jLabel_title = new javax.swing.JLabel();
        jButton_addProduct = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        java.awt.GridBagLayout layout = new java.awt.GridBagLayout();
        layout.columnWidths = new int[] {0, 12, 0, 12, 0};
        layout.rowHeights = new int[] {0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0};
        getContentPane().setLayout(layout);

        jLabel_productId.setText("Product ID:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        getContentPane().add(jLabel_productId, gridBagConstraints);

        jTextField_productIdInput.setMinimumSize(new java.awt.Dimension(300, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(jTextField_productIdInput, gridBagConstraints);

        jTextField_productNameInput.setMinimumSize(new java.awt.Dimension(100, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(jTextField_productNameInput, gridBagConstraints);

        jTextField_productPrice.setMinimumSize(new java.awt.Dimension(100, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(jTextField_productPrice, gridBagConstraints);

        jTextField_productStock.setMinimumSize(new java.awt.Dimension(100, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(jTextField_productStock, gridBagConstraints);

        jLabel_productName.setText("Product Name:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        getContentPane().add(jLabel_productName, gridBagConstraints);

        jLabel_productCategory.setText("Product Category:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        getContentPane().add(jLabel_productCategory, gridBagConstraints);

        jLabel_productPrice.setText("Product Price:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        getContentPane().add(jLabel_productPrice, gridBagConstraints);

        jLabel_productStock.setText("Product Stock:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        getContentPane().add(jLabel_productStock, gridBagConstraints);

        jComboBox_productCategoryCmbBx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(jComboBox_productCategoryCmbBx, gridBagConstraints);

        jLabel_title.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel_title.setText("Agregar Producto");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        getContentPane().add(jLabel_title, gridBagConstraints);

        jButton_addProduct.setText("Add Product");
        jButton_addProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_addProductActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.gridwidth = 5;
        getContentPane().add(jButton_addProduct, gridBagConstraints);

        setBounds(0, 0, 416, 331);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_addProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_addProductActionPerformed
        Category c = new Category();
        String[] stringArray = jComboBox_productCategoryCmbBx.getSelectedItem().toString().split(" - ");
        int catId = Integer.parseInt(stringArray[0]);
        String catName = stringArray[1];
        
        Product p = new Product(Integer.parseInt(jTextField_productIdInput.getText()),
                jTextField_productNameInput.getText(),
                new Category(catId, catName),
                Integer.parseInt(jTextField_productPrice.getText()),
                Integer.parseInt(jTextField_productStock.getText()));
        
        int option = JOptionPane.showConfirmDialog(this, "Are you sure you want to add this product?", "Confirmation",JOptionPane.YES_NO_CANCEL_OPTION);
        if (option == 0)
        {
            pc.addProduct(p);
            JOptionPane.showMessageDialog(this, "Product added succesfully.", "Confirmation",JOptionPane.INFORMATION_MESSAGE);
        }
        this.dispose();
    }//GEN-LAST:event_jButton_addProductActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                AddProductView dialog = new AddProductView(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    private void updateComboBox() {
        String[] comboBoxModel = cc.getAllCategories()
                .stream()
                .map(x -> x.getCategoryId() + " - " + x.getCategoryName())
                .toArray(size -> new String[size]);

        ComboBoxModel<String> model = new DefaultComboBoxModel(comboBoxModel);
        jComboBox_productCategoryCmbBx.setModel(model);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_addProduct;
    private javax.swing.JComboBox<String> jComboBox_productCategoryCmbBx;
    private javax.swing.JLabel jLabel_productCategory;
    private javax.swing.JLabel jLabel_productId;
    private javax.swing.JLabel jLabel_productName;
    private javax.swing.JLabel jLabel_productPrice;
    private javax.swing.JLabel jLabel_productStock;
    private javax.swing.JLabel jLabel_title;
    private javax.swing.JTextField jTextField_productIdInput;
    private javax.swing.JTextField jTextField_productNameInput;
    private javax.swing.JTextField jTextField_productPrice;
    private javax.swing.JTextField jTextField_productStock;
    // End of variables declaration//GEN-END:variables
}
