/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package inventorymanager.view;

import inventorymanager.controller.ProductController;
import inventorymanager.model.Category;
import inventorymanager.model.Product;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Gabote
 */
public class MainView extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainView.class.getName());
    private final ProductController pc;

    /**
     * Creates new form MainView
     */
    public MainView() {
        initComponents();

        //Custom code
        this.pc = new ProductController();
        updateGui();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jButton2 = new javax.swing.JButton();
        jLabel_title = new javax.swing.JLabel();
        jButton_addBttn = new javax.swing.JButton();
        jButton_updateBttn = new javax.swing.JButton();
        jButton_deleteBttn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_viewTable = new javax.swing.JTable();

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        java.awt.GridBagLayout layout = new java.awt.GridBagLayout();
        layout.columnWidths = new int[] {0, 12, 0, 12, 0};
        layout.rowHeights = new int[] {0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0};
        getContentPane().setLayout(layout);

        jLabel_title.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel_title.setText("Inventroy Management");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        getContentPane().add(jLabel_title, gridBagConstraints);

        jButton_addBttn.setText("Add Product");
        jButton_addBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_addBttnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        getContentPane().add(jButton_addBttn, gridBagConstraints);

        jButton_updateBttn.setText("Update Product");
        jButton_updateBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_updateBttnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(jButton_updateBttn, gridBagConstraints);

        jButton_deleteBttn.setText("Delete Product");
        jButton_deleteBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_deleteBttnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        getContentPane().add(jButton_deleteBttn, gridBagConstraints);

        jTable_viewTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "product_id", "product_name", "product_category", "product_price", "product_stock"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_viewTable.setFillsViewportHeight(true);
        jTable_viewTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable_viewTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable_viewTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable_viewTable);
        jTable_viewTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridheight = 9;
        getContentPane().add(jScrollPane1, gridBagConstraints);

        setBounds(0, 0, 658, 579);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_addBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_addBttnActionPerformed
        AddProductView addView = new AddProductView(this, true);

        addView.setVisible(true);
    }//GEN-LAST:event_jButton_addBttnActionPerformed

    private void jButton_updateBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_updateBttnActionPerformed
        JTable t = jTable_viewTable;
        try {
            int row = t.getSelectedRow();

            Product p = new Product();
            p.setProductId(Integer.parseInt(t.getValueAt(row, 0).toString()));
            p.setProductName(t.getValueAt(row, 1).toString());

            String[] catAtrib = t.getValueAt(row, 2).toString().split(" - ");
            p.setProductCategory(new Category(Integer.parseInt(catAtrib[0]), catAtrib[1]));
            p.setProductPrice(Integer.parseInt(t.getValueAt(row, 3).toString()));
            p.setProductStock(Integer.parseInt(t.getValueAt(row, 4).toString()));

            UpdateProductView updateView = new UpdateProductView(this, true, p);

            updateView.setVisible(true);

            updateGui();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "You didn't choose a product.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton_updateBttnActionPerformed

    private void jButton_deleteBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_deleteBttnActionPerformed
        JTable t = jTable_viewTable;
        int row = t.getSelectedRow();
        int id = Integer.parseInt(t.getValueAt(row, 0).toString());

        int option = JOptionPane.showConfirmDialog(this, "Are you sure you want to delete this product?", "Confirmation", JOptionPane.YES_NO_CANCEL_OPTION);

        if (option == 0) {
            pc.deleteProduct(id);
            updateGui();
            JOptionPane.showMessageDialog(this, "Product deleted succesfully.", "Confirmation", JOptionPane.INFORMATION_MESSAGE);
        }

    }//GEN-LAST:event_jButton_deleteBttnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainView().setVisible(true));
    }

    //CUSTOM CODE
    private void updateGui() {

        List<Product> productList = pc.getAllProducts();

        DefaultTableModel model = (DefaultTableModel) jTable_viewTable.getModel();

        model.setNumRows(0);

        productList.forEach(
                x -> {
                    Object[] row = {
                        x.getProductId(),
                        x.getProductName(),
                        x.getProductCategory().getCategoryId() + " - " + x.getProductCategory().getCategoryName(),
                        x.getProductPrice(),
                        x.getProductStock()
                    };

                    model.addRow(row);
                }
        );

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton_addBttn;
    private javax.swing.JButton jButton_deleteBttn;
    private javax.swing.JButton jButton_updateBttn;
    private javax.swing.JLabel jLabel_title;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_viewTable;
    // End of variables declaration//GEN-END:variables
}
